# S02 T04 Pràctica amb programació numèrica

### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [23]:
import numpy as np 

def array1D(arrayX):
    if arrayX.ndim == 1: 
        print("\nLa mitja de l'array és: ", arrayX.mean())
        print("\nLa diferencia d'extrems de l'array és: ", arrayX.ptp())
        print("\nLa variança de l'array és: ", arrayX.var())
        print("\nLa desviació standard de l'array és:  {:.3f} ".format(arrayX.std()))
        print("\nEl coeficient de variació de l'array és:  {:.3f} ".format(arrayX.mean() / arrayX.std()))
        
    else:
        dimensions = arrayY.shape()
        printnt("La matriu introduïda no és unidimensional sinó que té {} dimensions".format(dimensions))
        arrayX = arrayX.ravel('C')

            
arrayY = np.random.randint(1,100,50)
print(arrayY)
print("\n", arrayY.shape)
print(type(arrayY))

array1D(arrayY)

[20  5 72 25 16 64 34 56  3 27 59 41 39 59 33  7 66 49 68 87 35 17 46 69
 55 79 47  7 90 89 94 52 42 25 69 79 39 39 47 20 94 47 98 66 63 52  1 89
 41 25]

 (50,)
<class 'numpy.ndarray'>

La mitja de l'array és:  48.92

La diferencia d'extrems de l'array és:  97

La variança de l'array és:  692.6736

La desviació standard de l'array és:  26.319 

El coeficient de variació de l'array és:  1.859 


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [30]:
def matriuQuadrada(dim):
    
    matriZ = np.random.randint(0,100)
    print(matriZ)
    return [[matriZ for j in range(dim)] for i in range(dim)]

dim = 8   
matriuQuadrada(dim)   


42


[[42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42],
 [42, 42, 42, 42, 42, 42, 42, 42]]

### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [38]:
def sumaTotals(arrayX):
    sumar_Rows = np.sum(arrayX, axis=1)
    sumar_Cols = np.sum(arrayX, axis=0)
    print("\nTotal de files: {} \nTotal de columnes: {}".format(sumar_Rows, sumar_Cols))
    
arrayB = np.random.randint(40, size=(5, 6)) 
print(arrayB)
    
sumaTotals(arrayB)

[[21 37 31  4 35 37]
 [37  2 32 31  1 12]
 [18  8 37 28 38 26]
 [22  1 31  2 12 31]
 [33 16 19 37 17 27]]

Total de files: [165 115 155  99 149] 
Total de columnes: [131  64 150 102 103 133]


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

El coeficient de correlació s'utiliza per comparar variables cuantitatives i continues. Fem servir el corrcoef() inclós en la llibreria numpy per calcular el seu valor.

Si les variables aleatòries tenen associacions lineals altes, aleshores el seu coeficient de correlació és proper a +1 o -1. D'altra banda, les variables estadísticament independents tenen coeficients de correlació propers a zero.


La fórmula per calcular-lo:

![coeficient-correlacio](https://miro.medium.com/max/962/1*9qWpwVlIqqOBZ2IyGypX9g.jpeg)


In [57]:
import numpy as np
import scipy.stats

def calcul_CoeCorr(array1, array2):
    r = np.mean(np.multiply((array1-np.mean(array1)),(array2-np.mean(array2))))/(np.std(array1)*np.std(array2))
    print(r)  

#stat, p = scipy.stats.pearsonr(x, y)    

arrayT = np.random.randint(0,100, 10)
arrayH = np.random.randint(0,20, 10)

# Amb funció
print("\n____Metode numpy____\n")
calcul_CoeCorr(arrayT, arrayH)

# Sense funció
r2 = np.corrcoef (arrayT, arrayH) [0,1]
print(r2)

# Amb la llibreria Scipy
# p = valor p > si valor de p és menor que .05, conclouríem que hi ha una correlació estadísticament significativa entre 
# amdues variables.
print("\n____Metode scipy____\n")
stat, p = scipy.stats.pearsonr(arrayT, arrayH)
print(stat, p)


____Metode numpy____

0.15426023130693342
0.15426023130693342

____Metode scipy____

0.1542602313069334 0.6704716422739829
